name: Custom vcpkg registry tester

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VCPKG_COMMIT_SHA: 56bb2411609227288b70117ead2c47585ba07713 # corresponds to tag 2026.04.27

jobs:
  cross-platform-test-build:
    name: Cross platform test build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Windows-msvc2022
            os: windows-2022
            compiler: msvc-2022
            build-cversion: 17
            build-runtime: MD
            build-config: Release
            build-arch: x86_64

    steps:
      - name: Checkout registry repo
        uses: actions/checkout@v6

      - name: Set up binary cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ runner.temp }}/vcpkg-cache
          key: vcpkg-cache-${{ runner.os }}-${{ matrix.os }}-${{ matrix.build-cversion }}-${{ env.VCPKG_COMMIT_SHA }}-${{ hashFiles('**/vcpkg.json', '**/vcpkg-overlays/**') }}
          restore-keys: |
            vcpkg-cache-${{ runner.os }}-${{ matrix.os }}-${{ matrix.build-cversion }}-${{ env.VCPKG_COMMIT_SHA }}
  
      - name: Clone vcpkg
        uses: actions/checkout@v6
        with:
          repository: microsoft/vcpkg
          path: .vcpkg

      - name: Set vcpkg environment (Windows)
        if: startsWith(runner.os, 'Windows')
        shell: pwsh
        run: |
          echo "VCPKG_ROOT=${{ github.workspace }}\.vcpkg" >> $env:GITHUB_ENV

      - name: Bootstrap vcpkg (Windows)
        if: startsWith(runner.os, 'Windows')
        run: | 
          ${{ github.workspace }}\.vcpkg\bootstrap-vcpkg.bat -disableMetrics
          echo ${{ github.workspace }}\.vcpkg\ >> $GITHUB_PATH

      - name: Set vcpkg config file (Windows)
        if: startsWith(runner.os, 'Windows')
        shell: pwsh
        run: |
          echo "VCPKG_FEATURE_FLAGS=registries" >> $env:GITHUB_ENV
          echo "VCPKG_CONFIG_FILE=${{ github.workspace }}\test\registry-tester\vcpkg-configuration.json" >> $env:GITHUB_ENV
          dir ${{ github.workspace }}
          dir ${{ github.workspace }}\ports
          dir ${{ github.workspace }}\ports\qt
          dir ${{ github.workspace }}\versions
          dir ${{ github.workspace }}\versions\q-

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: Configure tester project   # this drives the port build
        if: startsWith(runner.os, 'Windows')
        working-directory: test\registry-tester
        run: |
          $python = Join-Path $env:pythonLocation "python.exe"
          echo "python at $python"
          cmake --preset vcpkg-windows -S . -B .\build "-DPYTHON3_EXECUTABLE=$python"

      - name: Upload vcpkg install log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-manifest-install-log
          path: test/registry-tester/build/vcpkg-manifest-install.log
      - name: Build tester
        working-directory: test\registry-tester
        run: cmake --build .\build