name: Custom vcpkg registry tester

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VCPKG_COMMIT_SHA: 56bb2411609227288b70117ead2c47585ba07713 # corresponds to tag 2026.04.27

jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix_setup.outputs.matrix }}
    steps:
    - name: Get matrix from file
      id: matrix_setup
      uses: ManiVaultStudio/github-actions/matrix_setup@main

  cross-platform-test-build:
    name: Cross platform test build
    needs: prepare_matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.prepare_matrix.outputs.matrix) }}

    steps:
      - name: Checkout registry repo
        uses: actions/checkout@v6

      - name: Set up binary cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ runner.temp }}/vcpkg-cache
          key: vcpkg-cache-${{ runner.os }}-${{ matrix.os }}-${{ matrix.build-cversion }}-${{ env.VCPKG_COMMIT_SHA }}-${{ hashFiles('**/vcpkg.json', '**/vcpkg-overlays/**') }}
          restore-keys: |
            vcpkg-cache-${{ runner.os }}-${{ matrix.os }}-${{ matrix.build-cversion }}-${{ env.VCPKG_COMMIT_SHA }}

  
      - name: Clone vcpkg
        uses: actions/checkout@v6
        with:
          repository: microsoft/vcpkg
          path: .vcpkg

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: Bootstrap vcpkg and python
        shell: pwsh
        run: | 
          $vcpkgRoot = Join-Path "${{ github.workspace }}" ".vcpkg"
          echo "VCPKG_ROOT=$vcpkgRoot" >> $env:GITHUB_ENV
          if ($env:RUNNER_OS -eq "Windows") {
            & "${{ github.workspace }}\.vcpkg\bootstrap-vcpkg.bat" -disableMetrics
            $python = Join-Path $env:pythonLocation "python.exe"
          } else {
            & "${{ github.workspace }}\.vcpkg\bootstrap-vcpkg.sh" -disableMetrics
            $python = Join-Path $env:pythonLocation "bin" "python3"
          }
          Add-Content -Path $env:GITHUB_ENV -Value "PYTHON3_EXECUTABLE=$python"
          echo ${{ github.workspace }}\.vcpkg\ >> $GITHUB_PATH
          echo "VCPKG_FEATURE_FLAGS=registries" >> $env:GITHUB_ENV
          $config_path = Join-Path ${{ github.workspace }} test registry-tester vcpkg-configuration.json
          echo "VCPKG_CONFIG_FILE=$config-path" >> $env:GITHUB_ENV
          $test_workdir = Join-Path ${{ github.workspace }} test registry-tester
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_WORKDIR=$test_workdir"

      - name: Install required Python packages
        shell: pwsh
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install requests packaging colorama

      - name: Install Linux build dependencies and add pem chain to cert store
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build pkg-config
          sudo cp lkebartifactory.nl.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates

      - name: Configure tester project   # this drives the port build
        shell: pwsh
        env:
          VCPKG_KEEP_ENV_VARS: "PYTHON3_EXECUTABLE;SEVEN_ZIP_EXECUTABLE"
          VCPKG_BINARY_SOURCES: "clear;http,${{ secrets.VCPKG_ARTIFACTORY_URL }}/{name}/{version}/{triplet}/{sha},readwrite,Authorization: Bearer ${{ secrets.VCPKG_ARTIFACTORY_TOKEN }}" 
        run: |
          Set-Location "$env:TEST_WORKDIR"
          $sevenZip = (Get-Command 7z).Source
          echo "7z at $sevenZip"
          $env:SEVEN_ZIP_EXECUTABLE = $sevenZip
          $preset = if ($IsWindows) { "vcpkg-windows" }
            elseif ($IsLinux) { "vcpkg-linux" }
            else { "vcpkg-macos" }
          $buildDir = Join-Path "." "build"
          cmake --preset $preset -S . -B $buildDir  

      - name: Upload vcpkg install log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-manifest-install-log
          path: test/registry-tester/build/vcpkg-manifest-install.log
      - name: Build tester
        shell: pwsh
        run: | 
          Set-Location "$env:TEST_WORKDIR"
          cmake --build .\build